version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: DB
    restart: always 
    volumes:
      - ./mariadb_init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql 
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: tp3_db
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    networks:
      - tp3_net

  script:
    build: 
      context: ./config
      dockerfile: Dockerfile_PHP
    container_name: SCRIPT
    volumes:
      - ./src:/app
    networks:
      - tp3_net
    depends_on:
      - db

  http:
    image: nginx:latest
    container_name: HTTP
    ports:
      - "8080:80"
    volumes:
      - ./src:/app
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - tp3_net
    depends_on:
      - script 

networks:
  tp3_net:
    driver: bridge
    
volumes:
  db_data:
